### ISSUE TITLE
Dica: GitHub Pages

### ISSUE THREAD

**Issue by AlvaroIsrael** [YanPedro18/API-Frases#1]
Fala @YanPedro18 tudo bem? Tu consegue publicar de graça seu site utilizando o GithubPages aqui mesmo do Github.

Não sei se tu já conhece, mas como vi que seus repositórios estão no formato de .html e .css na maioria é uma boa forma de hospedar e divulgar seus projetos!

Aqui um link do github explicando como fazer: https://docs.github.com/pt/pages/getting-started-with-github-pages/creating-a-github-pages-site

Se precisar ou quiser alguma ajudar é só me avisar!

**Comment by AlvaroIsrael** [comment]
Dai tu pode colocar a URL ali no canto do repositório pra facilitar a galera de visualizar, aqui um exemplo:

![image](https://user-images.githubusercontent.com/8402007/227385774-99371560-2e12-4494-a161-c5782830f745.png)

**Comment by YanPedro18** [comment]
Eu já sabia disso, todos os repo tem o gitpages para visualizar os
projetos, mas colocarei o link para o pessoal acessar, top!!! Valeu boa
noite Alvaro
Em qui., 23 de mar. de 2023 às 20:21, Alvaro Israel Nunes Leite <
***@***.***> escreveu:

**Comment by AlvaroIsrael** [comment]
Show, vou fechar essa issue, abri mesmo só para comentar, porque vi o post no LinkedIn! Sucesso!
